language: cpp
if: tag IS present
git:
  depth: 1
env:
  global:
    - MODULE_NAME=sourcenet
      REPOSITORY_DIR="$TRAVIS_BUILD_DIR"
      DEPENDENCIES="$TRAVIS_BUILD_DIR/dependencies"
      GARRYSMOD_COMMON="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common"
      SOURCE_SDK="$TRAVIS_BUILD_DIR/dependencies/sourcesdk-minimal"
      BUILD_SCRIPT="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common/build/build.sh"
      GARRYSMOD_COMMON_REPOSITORY="https://github.com/danielga/garrysmod_common.git"
      BOOTSTRAP_URL="https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.sh"
      TARGET_OS="$TRAVIS_OS_NAME"
      COMPILER_PLATFORM=gmake
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - linux-libc-dev:i386
            - g++-8-multilib
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/linux/premake-core/premake5"
          PROJECT_OS=linux
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz"
      before_install:
        - export CC=gcc-8
          export CXX=g++-8
    - os: osx
      osx_image: xcode9.4
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/macosx/premake-core/premake5"
          PROJECT_OS=macosx
          PREMAKE5_URL="https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-macosx.tar.gz"
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/dependencies"
install: "curl -s -L \"$BOOTSTRAP_URL\" | bash"
script: "$BUILD_SCRIPT"
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmsv_${MODULE_NAME}_${TARGET_OS}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmcl_${MODULE_NAME}_${TARGET_OS}.dll"
  on:
    tags: true
  api_key:
    secure: LMpBzhJGJMqXfsb2Fx89Cez72ZdDuRk7Y/nWJQykP3C5bIr1Xiobwib2zN6naMVoOt3uIhE4cRyhLZRuBCEMEs0/VU85hJ+JV8aYWNL2lxDssNBnoGxEWk5WOhRHK0dYKFCeX/JnVWQTtpKHL3+PAyj6rnqNOedYW0XoS9bH/vUEJGJ2EJBzJka5JT60FYBrMUkqsOMBloDqNU7sv06Am96bsqB6cXNiG1mNG08x2nmHd1ozxJMTKPDyy+L9y665nRCOYZRKoil4kw7Wc9Vqzco6IYIK6uBgy70e5zizixZ1LnNjz0ilj/2JVmsZbgDJwSo0p28iLElPDSa2I2mzr+I5p/1i4MDHF2J/MZrGsVfHyI+TvUx+EcbGYXWs1CtF9PoRKmfVNKu220+rBJNECHSVcA0LIg/RkUkBEwX6p3btURccgEademDOZ/qU4j5Hgxgf/ZXZ+iWg4jocq065fWUSecHETEJ+UFmN5sod+F6RRB3e9lvslQ5yzCLv+RMBvRntnYXC+MchTb3WF9FbPIAfw2rcplg+pjs0bPboqei/mBX5P98hKXHy1HpoAnnXWw5PezLjYQsjWmEcFJkQPKpcD1h6yqeHtXmKSdpl1mJLBshJCBQ6tN7F6P6839CozKyFOowj613OHcC/BdyiTKLo4Ze083GDZw5XWbu0EQ4=
