language: cpp
if: tag IS present
git:
  depth: 1
env:
  global:
    - MODULE_NAME=sourcenet
      REPOSITORY_DIR="$TRAVIS_BUILD_DIR"
      DEPENDENCIES="$TRAVIS_BUILD_DIR/dependencies"
      GARRYSMOD_COMMON="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common"
      SOURCE_SDK="$TRAVIS_BUILD_DIR/dependencies/sourcesdk-minimal"
      TARGET_OS="$TRAVIS_OS_NAME"
      COMPILER_PLATFORM=gmake
      BUILD_SCRIPT="$TRAVIS_BUILD_DIR/dependencies/garrysmod_common/build/ci.sh"
      GARRYSMOD_COMMON_REPOSITORY="https://github.com/danielga/garrysmod_common.git"
      PREMAKE5_EXECUTABLE=premake5
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - linux-libc-dev:i386
            - g++-8-multilib
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/linux/premake-core/premake5"
          PROJECT_OS=linux
      before_install:
        - export CC=gcc-8
          export CXX=g++-8
    - os: osx
      osx_image: xcode9.4
      env:
        - PREMAKE5="$TRAVIS_BUILD_DIR/dependencies/macosx/premake-core/premake5"
          PROJECT_OS=macosx
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/dependencies"
    - "$TRAVIS_BUILD_DIR/projects"
install:
  - mkdir -p "$DEPENDENCIES"
  - if [ ! -f "$GARRYSMOD_COMMON/premake5.lua" ]; then
      echo "garrysmod_common directory is empty, doing git clone of the remote repo";
      git clone --recursive "$GARRYSMOD_COMMON_REPOSITORY" "$GARRYSMOD_COMMON";
    else
      echo "garrysmod_common directory is good, pulling any latest changes";
      git -C "$GARRYSMOD_COMMON" pull;
      git -C "$GARRYSMOD_COMMON" submodule update --init --recursive;
    fi
script: "$BUILD_SCRIPT"
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmsv_${MODULE_NAME}_${TARGET_OS}.dll"
    - "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmcl_${MODULE_NAME}_${TARGET_OS}.dll"
  on:
    tags: true
  api_key:
    secure: LMpBzhJGJMqXfsb2Fx89Cez72ZdDuRk7Y/nWJQykP3C5bIr1Xiobwib2zN6naMVoOt3uIhE4cRyhLZRuBCEMEs0/VU85hJ+JV8aYWNL2lxDssNBnoGxEWk5WOhRHK0dYKFCeX/JnVWQTtpKHL3+PAyj6rnqNOedYW0XoS9bH/vUEJGJ2EJBzJka5JT60FYBrMUkqsOMBloDqNU7sv06Am96bsqB6cXNiG1mNG08x2nmHd1ozxJMTKPDyy+L9y665nRCOYZRKoil4kw7Wc9Vqzco6IYIK6uBgy70e5zizixZ1LnNjz0ilj/2JVmsZbgDJwSo0p28iLElPDSa2I2mzr+I5p/1i4MDHF2J/MZrGsVfHyI+TvUx+EcbGYXWs1CtF9PoRKmfVNKu220+rBJNECHSVcA0LIg/RkUkBEwX6p3btURccgEademDOZ/qU4j5Hgxgf/ZXZ+iWg4jocq065fWUSecHETEJ+UFmN5sod+F6RRB3e9lvslQ5yzCLv+RMBvRntnYXC+MchTb3WF9FbPIAfw2rcplg+pjs0bPboqei/mBX5P98hKXHy1HpoAnnXWw5PezLjYQsjWmEcFJkQPKpcD1h6yqeHtXmKSdpl1mJLBshJCBQ6tN7F6P6839CozKyFOowj613OHcC/BdyiTKLo4Ze083GDZw5XWbu0EQ4=
